joint_limits:
  body_roll_joint:
    has_position_limits: true
    min_position: -4.14
    max_position: 4.14
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  head_tilt_joint:
    has_position_limits: true
    min_position: -0.45
    max_position: 0.45
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  head_pan_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  r_arm_shoulder_roll_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 3.14 #1.57
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  r_arm_shoulder_pan_joint:
    has_position_limits: true
    min_position: -1.22
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  r_arm_elbow_tilt_joint:
    has_position_limits: true
    min_position: 0.0
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  r_arm_wrist_tilt_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  r_hand_joint:
    has_position_limits: true
    min_position: 0
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  l_arm_shoulder_roll_joint: #The function here is negative, so min is max and max is min
    has_position_limits: true
    min_position: -3.14
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  l_arm_shoulder_pan_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.22
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  l_arm_elbow_tilt_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 0.0
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  l_arm_wrist_tilt_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  l_hand_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 0
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0