hardware:
  publish_rate: 10

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 10

body_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    #- body_lift_joint
    - body_roll_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05
  allow_partial_joints_goal: true

head_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - head_tilt_joint
    - head_pan_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05
  allow_partial_joints_goal: true

# right_arm_trajectory_controller:
r_arm_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - r_arm_shoulder_roll_joint
    - r_arm_shoulder_pan_joint
    - r_arm_elbow_tilt_joint
    - r_arm_wrist_tilt_joint
    - r_hand_joint
    # - right_shoulder_roll_joint
    # - right_shoulder_flex_joint
    # - right_elbow_roll_joint
    # - right_hand_motor_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05
  allow_partial_joints_goal: true

# left_arm_trajectory_controller:
l_arm_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - l_arm_shoulder_roll_joint
    - l_arm_shoulder_pan_joint
    - l_arm_elbow_tilt_joint
    - l_arm_wrist_tilt_joint
    - l_hand_joint
    # - left_shoulder_roll_joint
    # - left_shoulder_flex_joint
    # - left_elbow_roll_joint
    # - left_hand_motor_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05
  allow_partial_joints_goal: true

dynamixel_port:
  port_name: "/dev/input/dynamixel1"
  baud_rate: 1000000
  joints:
    - l_arm_shoulder_roll_joint
    - l_arm_shoulder_pan_joint
    - l_arm_elbow_tilt_joint
    - l_arm_wrist_tilt_joint
    - l_hand_joint
    - r_arm_shoulder_roll_joint
    - r_arm_shoulder_pan_joint
    - r_arm_elbow_tilt_joint
    - r_arm_wrist_tilt_joint
    - r_hand_joint
    - body_roll_joint
    - head_pan_joint
    - head_tilt_joint

    #- body_lift_joint

    # - body_roll_joint
    # - head_tilt_joint
    # - head_pan_joint
    # - right_shoulder_roll_joint
    # - right_shoulder_flex_joint
    # - right_elbow_roll_joint
    # - right_hand_motor_joint
    # - left_shoulder_roll_joint
    # - left_shoulder_flex_joint
    # - left_elbow_roll_joint
    # - left_hand_motor_joint
  l_arm_shoulder_roll_joint:  {id: 11, center: 2048, home: 0.0, mode: 3, vel: 120, acc: 0, pos_d_gain: 0, pos_i_gain: 300, pos_p_gain: 0, gear_ratio: 1 }
  l_arm_shoulder_pan_joint:   {id: 12, center: 2048, home: -1.25, mode: 3, vel: 120, acc: 0, pos_d_gain: 0, pos_i_gain: 300, pos_p_gain: 0, gear_ratio: 1 }
  l_arm_elbow_tilt_joint:     {id: 13, center: 2048, home: 0.0, mode: 3, vel: 200, acc: 0, pos_d_gain: 0, pos_i_gain: 300, pos_p_gain: 0, gear_ratio: 1 }
  l_arm_wrist_tilt_joint:     {id: 14, center: 2048, home: 0.0, mode: 3, vel: 200, acc: 0, pos_d_gain: 0, pos_i_gain: 300, pos_p_gain: 0, gear_ratio: 1 }
  l_hand_joint:               {id: 15, center: 2048, home: 0.0, mode: 5, vel: 0, acc: 0, pos_d_gain: 0, pos_i_gain: 0, pos_p_gain: 0, lim: 150, gear_ratio: 1 }
  r_arm_shoulder_roll_joint:  {id: 21, center: 2048, home: 0.0, mode: 3, vel: 120, acc: 0, pos_d_gain: 0, pos_i_gain: 300, pos_p_gain: 0, gear_ratio: 1 }
  r_arm_shoulder_pan_joint:   {id: 22, center: 2048, home: 1.25, mode: 3, vel: 120, acc: 0, pos_d_gain: 0, pos_i_gain: 300, pos_p_gain: 0, gear_ratio: 1 }
  r_arm_elbow_tilt_joint:     {id: 23, center: 2048, home: 0.0, mode: 3, vel: 200, acc: 0, pos_d_gain: 0, pos_i_gain: 300, pos_p_gain: 0, gear_ratio: 1 }
  r_arm_wrist_tilt_joint:     {id: 24, center: 2048, home: 0.0, mode: 3, vel: 200, acc: 0, pos_d_gain: 0, pos_i_gain: 300, pos_p_gain: 0, gear_ratio: 1 }
  r_hand_joint:               {id: 25, center: 2048, home: 0.0, mode: 5, vel: 0, acc: 0, pos_d_gain: 0, pos_i_gain: 0, pos_p_gain: 0, lim: 150, gear_ratio: 1 }
  body_roll_joint:            {id: 2, center: 2048, home: 0.0, mode: 3, vel: 200, acc: 0, pos_d_gain: 0, pos_i_gain: 300, pos_p_gain: 0, gear_ratio: 5.2727 }
  head_pan_joint:             {id: 3, center: 2048, home: 0.0, mode: 3, vel: 200, acc: 0, pos_d_gain: 0, pos_i_gain: 300, pos_p_gain: 0, gear_ratio: 1 }
  head_tilt_joint:            {id: 4, center: 2048, home: 0.0, mode: 3, vel: 200, acc: 0, pos_d_gain: 0, pos_i_gain: 300, pos_p_gain: 0, gear_ratio: 2.04348 }
  #body_lift_joint: {id: 16, center: 2048, home: 2048, mode: 3, vel: 0, acc: 0, pos_i_gain: 300}
  # body_roll_joint: {id: 2, center: 2048, home: 0.0, mode: 3, vel: 0, acc: 0, pos_i_gain: 300, gear_ratio: 5.2727 }
  # head_tilt_joint: {id: 3, center: 2048, home: 0.0, mode: 3, vel: 0, acc: 0, pos_i_gain: 300, gear_ratio: 2.04348 }
  # head_pan_joint: {id: 4, center: 2560, home: 0.0, mode: 3, vel: 0, acc: 0, pos_i_gain: 300, gear_ratio: 1 }
  # right_shoulder_roll_joint: {id: 10, center: 2048, home: 0.0, mode: 3, vel: 0, acc: 0, pos_i_gain: 300, gear_ratio: 1 }
  # right_shoulder_flex_joint: {id: 11, center: 2048, home: -1.25, mode: 3, vel: 0, acc: 0, pos_i_gain: 300, gear_ratio: 1 }
  # right_elbow_roll_joint: {id: 12, center: 2048, home: 0.0, mode: 3, vel: 0, acc: 0, pos_i_gain: 300, gear_ratio: 1 }
  # right_hand_motor_joint: {id: 13, center: 1410, home: 0.0, mode: 5, vel: 0, acc: 0, pos_i_gain: 0, lim: 200, gear_ratio: 1 }
  # left_shoulder_roll_joint: {id: 20, center: 2048, home: 0.0, mode: 3, vel: 0, acc: 0, pos_i_gain: 300, gear_ratio: 1 }
  # left_shoulder_flex_joint: {id: 21, center: 3584, home: -1.25, mode: 3, vel: 0, acc: 0, pos_i_gain: 300, gear_ratio: 1 }
  # left_elbow_roll_joint: {id: 22, center: 2560, home: 0.0, mode: 3, vel: 0, acc: 0, pos_i_gain: 300, gear_ratio: 1 }
  # left_hand_motor_joint: {id: 23, center: 1410, home: 0.0, mode: 5, vel: 0, acc: 0, pos_i_gain: 0, lim: 200, gear_ratio: 1 }