hardware:
  publish_rate: 10

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 20

body_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - body_lift_joint
    - body_roll_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05
  allow_partial_joints_goal: true

head_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - head_tilt_joint
    - head_pan_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05
  allow_partial_joints_goal: true

right_arm_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - right_shoulder_roll_joint
    - right_shoulder_flex_joint
    - right_wrist_flex_joint
    - right_hand_motor_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05
  allow_partial_joints_goal: true

left_arm_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_shoulder_roll_joint
    - left_shoulder_flex_joint
    - left_wrist_flex_joint
    - left_hand_motor_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05
  allow_partial_joints_goal: true