hardware:
  publish_rate: 10

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 10

l_arm_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - l_arm_shoulder_roll_joint
    - l_arm_shoulder_pan_joint
    - l_arm_elbow_tilt_joint
    - l_arm_wrist_tilt_joint
    - l_hand_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05
  allow_partial_joints_goal: true