/**:
  ros__parameters:
    poses:
      - initial_pose
      - detecting_pose

    initial_pose:
      r_arm_shoulder_roll :  0.0
      r_arm_shoulder_pan  :  1.25
      r_arm_elbow_tilt    :  0.0
      r_arm_wrist_tilt    :  0.0
      r_hand              :  0.0
      l_arm_shoulder_roll :  0.0
      l_arm_shoulder_pan  : -1.25
      l_arm_elbow_tilt    :  0.0
      l_arm_wrist_tilt    :  0.0
      l_hand              :  0.0
      body_roll           :  0.0
      head_camera_pan     :  0.0
      head_camera_tilt    :  0.0

    detecting_pose:
      r_arm_shoulder_roll : -0.78
      r_arm_shoulder_pan  :  1.25
      r_arm_elbow_tilt    :  1.57
      r_arm_wrist_tilt    :  1.57
      r_hand              :  0.0
      l_arm_shoulder_roll :  0.78
      l_arm_shoulder_pan  : -1.25
      l_arm_elbow_tilt    : -1.57
      l_arm_wrist_tilt    : -1.57
      l_hand              :  0.0
      body_roll           :  0.0
      head_camera_pan     :  0.0
      head_camera_tilt    : -0.4